# Generated by Django 5.2.8 on 2026-01-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code ISO (ex: fr, nl, en, fr-BE)', max_length=10, unique=True, verbose_name='code')),
                ('name', models.CharField(help_text='Nom lisible (ex: Français, Nederlands, English)', max_length=100, verbose_name='name')),
                ('active', models.BooleanField(default=True, help_text="Langue disponible pour la saisie et l'affichage", verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['code'],
            },
        ),
    ]
