# Generated by Django 5.2.8 on 2026-04-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='new_password_asked',
            field=models.BooleanField(default=False),
        ),
    ]
