"""
Django settings for wpref project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEEPL_IS_FREE=(bool, False),
)
ENV_FILE = BASE_DIR / ".env"
environ.Env.read_env(str(ENV_FILE))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t6y&^m%4-jo!7ov3ux2-j53r87^=w4&^u%@o7pnfamcz_nvzi6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'schema_viewer',
    'corsheaders',
    'drf_spectacular',
    'django_filters',
    'django_extensions',
    'parler',

    'customuser.apps.CustomuserConfig',
    'subject.apps.SubjectConfig',
    'question.apps.QuestionConfig',
    'quiz.apps.QuizConfig',
    'domain.apps.DomainConfig',
    'language.apps.LanguageConfig',
    'translation.apps.TranslationConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wpref.urls'
AUTH_USER_MODEL = "customuser.CustomUser"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wpref.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []
#    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#    },
#    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#    },
#    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#    },
#    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#    },
# ]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGES = (
    ('en', _('English')),
    ('fr', _('French')),
    ('nl', _('Dutch')),
    ('it', _('Italy')),
    ('es', _('Spain')),
)

LANGUAGE_CODE = 'en'
TIME_ZONE = "Europe/Brussels"
USE_I18N = True
USE_TZ = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200", "http://127.0.0.1:4200"
]

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "rest_framework.views.exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"]
}

SPECTACULAR_SETTINGS = {
    "TITLE": "WpRef API",
    "VERSION": "1.0.0",
    # Le bouton Authorize persiste votre token entre les refresh
    "SWAGGER_UI_SETTINGS": {"persistAuthorization": True},
    # Appliquer le schéma de sécu par défaut à tous les endpoints
    # "SECURITY": [{"jwtAuth": []}],
    "ENUM_NAME_OVERRIDES": {
        "VisibilityEnum": "quiz.constants.VISIBILITY_CHOICES",
    },
    "COMPONENT_SPLIT_REQUEST": True,
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "no-reply@monapp.com"

SENSITIVE_FIELDS = {
    "password",
    "password1",
    "password2",
    "old_password",
    "new_password",
    "token",
    "access",
    "refresh",
    "api_key",
    "secret",
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

DEEPL_AUTH_KEY = env("DEEPL_AUTH_KEY", default="")
DEEPL_IS_FREE = env("DEEPL_IS_FREE")
